extends: airbnb-base
plugins:
  - import
env:
  browser: true
  node: true
  es6: true
rules:
  no-console: off         # Desactiva la regla no-console
  import/extensions: off   # Desactiva la regla import/extensions
  import/prefer-default-export: off